name: Publish

on:
  push:
    branches:
      - "release"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - "mustate"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - name: Publish package
        run: |
          yarn install
          yarn update-packages
          cp README.md packages/${{ matrix.package }}/README.md
          cp CHANGELOG.md packages/${{ matrix.package }}/CHANGELOG.md
          cd packages/${{ matrix.package }}
          yarn build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
